version: '3'

services:

  engine:
    build: ./engine
    image: engine:01
    container_name: engine-cont
    ports:
      - 9998:9998
      - 9876:9876
    networks:
      - sac20_net
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 4G
          

  locust-master:
    build: ./locust-master
    image: locust:01
    container_name: locust-master
    ports:
      - 5557:5557
      - 8089:8089
    networks:
      - sac20_net

  locust-slave01:
    build: ./locust-slave
    image: locust:01
    container_name: locust-master
    networks:
      - sac20_net

  locust-slave02:
    build: ./locust-slave
    image: locust:01
    container_name: locust-master
    networks:
      - sac20_net

  locust-slave03:
    build: ./locust-slave
    image: locust:01
    container_name: locust-master
    networks:
      - sac20_net

  locust-slave04:
    build: ./locust-slave
    image: locust:01
    container_name: locust-master
    networks:
      - sac20_net

networks:
  sac20_net:
    driver: bridge
